# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import mosaico.models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaico',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to=mosaico.models.get_mosaico_result_image_path, verbose_name='Out file'),
        ),
    ]
