# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imagefolder_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefolder',
            name='index',
        ),
    ]
