# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_imagefolder_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefolder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
